### PR TITLE
General Fix

### LINKED ISSUE #9: {{partial}} naming issue
When I try to render a partial, e.g. {{partial "test"}} I get this error: 
DEPRECATION: You tried to render the partial test, which should be at '_test', but Ember found 'test'. Please use a leading underscore in your partials
Even if I name the hbs file _test or add <script data-template-name="_test" type="text/x-handlebars-template">
Any idea why this could be?

### PR DESCRIPTION
**Pull request by MilkyWayJoe**
This fixes #9
- Updated `System.Web.Optimization` library;
- Updated `EmberHandlebarsBundleTransform` (in lib) and
  `HandlebarsBundleTransform` (in sample) classes;
- Updated Web API Sample.
- Added ember RC2 from NuGet;
- Added ember-data rev12 from NuGet;
- Added Web API Adapter & Serializer
- Modified folder structure;
- removed un-used View classes
- edited readme to display the NuGet install

Note: Sample currently referencing Ember.Handlebars.dll directly since
it hasn't been published as a new packaged yet;

### CODE REVIEW

File: Ember.Handlebars.ExampleWebAPI/App_Start/HandlebarsBundleTransform.cs [hunk 1]
```diff
@@ -6,7 +6,7 @@
 
 namespace Ember.Handlebars.ExampleWebAPI
 {
-    public class EmberHandlebarsBundleTransform : IBundleTransform
+    public class Emb_erHandlebarsBundleTransform : IBundleTransform
```
Comment (ZogStriP) [inline Ember.Handlebars.ExampleWebAPI/App_Start/HandlebarsBundleTransform.cs]: typo?

Comment (MilkyWayJoe) [inline Ember.Handlebars.ExampleWebAPI/App_Start/HandlebarsBundleTransform.cs]: totally
